#!/usr/bin/env bash

# change back localhost
sed -i 's/'${HOSTNAME%%.*}/LOCALHOST'/g' MessageFacility.fcl


function getStatus()
{
    status=`status.sh | grep String | awk '{print $2}' | tr -d "'"`
#    [ $1 != "$status" ] && (echo $status)
  echo $status
}

send_transition.sh stop
getStatus "nil"
while [ "$status" != 'ready' ]
do
  sleep 2
  getStatus "stopping"
done

send_transition.sh terminate
getStatus "nil"
while [ "$status" != 'stopped' ]
do
  sleep 2
  getStatus "terminating"
done

