#!/usr/bin/env bash
this_start=$(date +%s)

function getStatus()
{
  status=`status.sh | grep String | awk '{print $2}' | tr -d "'"`
#  [ $1 != "$status" ] && (echo $status)
  echo $status
}

getStatus "nil"
# [ $status == 'Existing'] && (kill_daqinterface_on_partition.sh 0; exit 0 )

# setdaqcomps.sh icarustpc01 icarustpc02 icarustpc03 icarustpc04

# BH MH: commenting out this line for now. For regular VST running, we want to use this...
# setdaqcomps.sh icarustpc01 icarustpc04

# BH MH: adding this line for now, to try using a 3rd crate
# DM: changing name convention
#setdaqcomps.sh icarustpc01 icarustpc04 icarustpcew07 icarustpcew09
setdaqcomps.sh icarustpc04 icarustpcwe07 icarustpcwe09 icarustpcew05 icarustpcew07 icarustpcew09


send_transition.sh boot boot.txt
getStatus "booting"
while [ "$status" != 'booted' ]
do
  sleep 2
  getStatus "booting"
  [ "$status" == 'stopped' ] && (kill_daqinterface_on_partition.sh $DAQINTERFACE_PARTITION_NUMBER; exit 1 )
done

send_transition.sh config standard
#send_transition.sh config testGALZ00004

getStatus "configuring"
while [ "$status" != 'ready' ]
do
  sleep 2
  getStatus "configuring"
  [ "$status" == 'stopped' ] && (kill_daqinterface_on_partition.sh $DAQINTERFACE_PARTITION_NUMBER; exit 1 )
  # [ "$status" == 'stopped' ] && ( exit 1 )
done
 
# report_datafile_location

send_transition.sh start
# getStatus "starting"
sleep 2
getStatus "starting"
while [ "$status" != 'running' ]
do
  sleep 2
  getStatus "starting"
  [ "$status" == 'stopped' ] && (kill_daqinterface_on_partition.sh $DAQINTERFACE_PARTITION_NUMBER; exit 1 )
done

this_stop=$(date +%s)
echo "DAQ started in $(( this_stop - this_start )) seconds."


