#!/usr/bin/env bash
this_start=$(date +%s)

function getStatus()
{
  status=`status.sh | grep String | awk '{print $2}' | tr -d "'"`
#  [ $1 != "$status" ] && (echo $status)
  echo $status
}

getStatus "nil"
# [ $status == 'Existing'] && (kill_daqinterface_on_partition.sh 0; exit 0 )


setdaqcomps.sh \
icaruspmteebot01 \
icaruspmteebot02 \
icaruspmteebot03 \
icaruspmteetop01 \
icaruspmteetop02 \
icaruspmteetop03 \
icaruspmtewbot01 \
icaruspmtewbot02 \
icaruspmtewbot03 \
icaruspmtewtop02 \
icaruspmtewtop03 \
icaruspmtwebot01 \
icaruspmtwebot02 \
icaruspmtwebot03 \
icaruspmtwetop01 \
icaruspmtwetop02 \
icaruspmtwetop03 \
icaruspmtwwbot01 \
icaruspmtwwbot02 \
icaruspmtwwbot03 \
icaruspmtwwtop01 \
icaruspmtwwtop02 \
icaruspmtwwtop03 \
icarustpcww01b \
icarustpcww01m \
icarustpcww01t \
icarustpcww02 \
icarustpcww03 \
icarustpcww04 \
icarustpcww05 \
icarustpcww06 \
icarustpcww07 \
icarustpcww08 \
icarustpcww09 \
icarustpcww10 \
icarustpcww11 \
icarustpcww12 \
icarustpcww13 \
icarustpcww14 \
icarustpcww15 \
icarustpcww16 \
icarustpcww17 \
icarustpcww18 \
icarustpcww19 \
icarustpcww20b \
icarustpcww20m \
icarustpcww20t \
icarustpcwe01b \
icarustpcwe01m \
icarustpcwe01t \
icarustpcwe02 \
icarustpcwe03 \
icarustpcwe04 \
icarustpcwe05 \
icarustpcwe06 \
icarustpcwe07 \
icarustpcwe08 \
icarustpcwe09 \
icarustpcwe10 \
icarustpcwe11 \
icarustpcwe12 \
icarustpcwe13 \
icarustpcwe14 \
icarustpcwe15 \
icarustpcwe16 \
icarustpcwe17 \
icarustpcwe18 \
icarustpcwe19 \
icarustpcwe20b \
icarustpcwe20m \
icarustpcwe20t 
icaruscrt01nno  \
icaruscrt01nni  \
icaruscrt03wci  \
icaruscrt03wco

send_transition.sh boot boot.txt
getStatus "booting"
while [ "$status" != 'booted' ]
do
  sleep 2
  getStatus "booting"
  [ "$status" == 'stopped' ] && (kill_daqinterface_on_partition.sh $DAQINTERFACE_PARTITION_NUMBER; exit 1 )
done

send_transition.sh config standard
#send_transition.sh config testGALQ

getStatus "configuring"
while [ "$status" != 'ready' ]
do
  sleep 2
  getStatus "configuring"
  [ "$status" == 'stopped' ] && (kill_daqinterface_on_partition.sh $DAQINTERFACE_PARTITION_NUMBER; exit 1 )
  # [ "$status" == 'stopped' ] && ( exit 1 )
done
 
# report_datafile_location

send_transition.sh start
# getStatus "starting"
sleep 2
getStatus "starting"
while [ "$status" != 'running' ]
do
  sleep 2
  getStatus "starting"
  [ "$status" == 'stopped' ] && (kill_daqinterface_on_partition.sh $DAQINTERFACE_PARTITION_NUMBER; exit 1 )
done

this_stop=$(date +%s)
echo "DAQ started in $(( this_stop - this_start )) seconds."


