#!/usr/bin/env bash
this_start=$(date +%s)

function getStatus()
{
  status=`status.sh | grep String | awk '{print $2}' | tr -d "'"`
#  [ $1 != "$status" ] && (echo $status)
  echo $status
}

getStatus "nil"
# [ $status == 'Existing'] && (kill_daqinterface_on_partition.sh 0; exit 0 )

# set component to use
#setdaqcomps.sh icarustpc04 icarustpcwe07 icarustpcwe09 icarustpcew05 icarustpcew07

#setdaqcomps.sh icarustpcwe05 icarustpcwe06 icarustpcwe07 icarustpcwe09 icarustpcew05 icarustpcew06 icarustpcew07 icarustpcew09
#setdaqcomps.sh icaruspmtewtop01 icaruspmtewtop02 icaruspmtewtop03 icaruspmtewbot01 icaruspmtewbot02 icaruspmtewbot03 icaruspmteetop01 icaruspmteetop02 icaruspmteetop03 icaruspmteebot01 icaruspmteebot02 icaruspmteebot03

# for tpc testing
setdaqcomps.sh icarustpcwe05

send_transition.sh boot boot.txt
getStatus "booting"
while [ "$status" != 'booted' ]
do
  sleep 2
  getStatus "booting"
  [ "$status" == 'stopped' ] && (kill_daqinterface_on_partition.sh $DAQINTERFACE_PARTITION_NUMBER; exit 1 )
done

send_transition.sh config standard
#send_transition.sh config testGALZ00004

getStatus "configuring"
while [ "$status" != 'ready' ]
do
  sleep 2
  getStatus "configuring"
  [ "$status" == 'stopped' ] && (kill_daqinterface_on_partition.sh $DAQINTERFACE_PARTITION_NUMBER; exit 1 )
  # [ "$status" == 'stopped' ] && ( exit 1 )
done
 
# report_datafile_location

send_transition.sh start
# getStatus "starting"
sleep 2
getStatus "starting"
while [ "$status" != 'running' ]
do
  sleep 2
  getStatus "starting"
  [ "$status" == 'stopped' ] && (kill_daqinterface_on_partition.sh $DAQINTERFACE_PARTITION_NUMBER; exit 1 )
done

this_stop=$(date +%s)
echo "DAQ started in $(( this_stop - this_start )) seconds."


