#!/bin/sh

ulimit -S -c unlimited

# Include the path to a built sbndaq-redis-plugin for use by the MetricManager.
# Temporary until we include a release in /software/products
export LD_LIBRARY_PATH=/home/nfs/gputnam/sbndaq2/build_slf7.x86_64/sbndaq-redis-plugin/lib:$LD_LIBRARY_PATH

export THIS_SBN_DAQ_DAQINTERFACE_DIR=$(dirname "${BASH_SOURCE[0]}")
export THIS_SBN_DAQ_DAQINTERFACE_DIR=$(realpath "$THIS_SBN_DAQ_DAQINTERFACE_DIR")

export DAQINTERFACE_PROCESS_MANAGEMENT_METHOD=direct
export DAQINTERFACE_SETTINGS=$THIS_SBN_DAQ_DAQINTERFACE_DIR/user_settings
export DAQINTERFACE_KNOWN_BOARDREADERS_LIST=$THIS_SBN_DAQ_DAQINTERFACE_DIR/known_boardreaders_list
export DAQINTERFACE_FHICL_DIRECTORY=$THIS_SBN_DAQ_DAQINTERFACE_DIR/configs
export DAQINTERFACE_CRITICAL_PROCESSES_LIST=$MYDAQ_CONFIG_DIR/critical_process_list

export DAQINTERFACE_MESSAGEFACILITY_FHICL=$THIS_SBN_DAQ_DAQINTERFACE_DIR/MessageFacility.fcl

export DAQINTERFACE_PARTITION_NUMBER=0

#export DAQINTERFACE_FHICL_DIRECTORY=IGNORED

if [[ ! -e $DAQINTERFACE_SETTINGS ]]; then
   echo "Unable to find settings file \"$DAQINTERFACE_SETTINGS\"" >&2
   export DAQINTERFACE_USER_SOURCEFILE_ERRNO=1
   return 
fi

if [[ ! -e $DAQINTERFACE_KNOWN_BOARDREADERS_LIST ]]; then
   echo "Unable to find boardreaders list file \"$DAQINTERFACE_KNOWN_BOARDREADERS_LIST\"" >&2
   export DAQINTERFACE_USER_SOURCEFILE_ERRNO=2
   return 
fi

if [[ "$DAQINTERFACE_FHICL_DIRECTORY" != "IGNORED" && ! -e $DAQINTERFACE_FHICL_DIRECTORY ]]; then
   echo "Unable to find FHiCL configuration directory \"$DAQINTERFACE_FHICL_DIRECTORY\"" >&2
   export DAQINTERFACE_USER_SOURCEFILE_ERRNO=3
   return
elif [[ "$DAQINTERFACE_FHICL_DIRECTORY" == "IGNORED" ]]; then
 
   echo "Put code here which sets up the database environment"

fi

export DAQINTERFACE_USER_SOURCEFILE_ERRNO=0
