#!/bin/sh

#ulimit -S -c unlimited
ulimit -S -c 0

export DAQINTERFACE_LOGDIR="/daq/log"

export THIS_SBN_DAQ_DAQINTERFACE_DIR=$(realpath $(dirname "${BASH_SOURCE[0]}"))
export DAQINTERFACE_SETTINGS=$THIS_SBN_DAQ_DAQINTERFACE_DIR/user_settings
export DAQINTERFACE_KNOWN_BOARDREADERS_LIST=$THIS_SBN_DAQ_DAQINTERFACE_DIR/known_boardreaders_list
export DAQINTERFACE_FHICL_DIRECTORY=$THIS_SBN_DAQ_DAQINTERFACE_DIR/configs
export DAQINTERFACE_MESSAGEFACILITY_FHICL=$THIS_SBN_DAQ_DAQINTERFACE_DIR/MessageFacility.fcl
export DAQINTERFACE_TRACE_SCRIPT=$THIS_SBN_DAQ_DAQINTERFACE_DIR/trace_control.sh

export DAQINTERFACE_PROCESS_MANAGEMENT_METHOD=direct

export DAQINTERFACE_PARTITION_NUMBER=1

echo "DAQINTERFACE_PARTITION_NUMBER=$DAQINTERFACE_PARTITION_NUMBER"
# export DAQINTERFACE_PORT=$(( $ARTDAQ_BASE_PORT + $DAQINTERFACE_PARTITION_NUMBER * $ARTDAQ_PORTS_PER_PARTITION ))

export DAQINTERFACE_CRITICAL_PROCESSES_LIST=$THIS_SBN_DAQ_DAQINTERFACE_DIR/critical_process_list

######################################################
##Uncomment  the line below to enable artdaq_database.#
export DAQINTERFACE_FHICL_DIRECTORY=IGNORED
######################################################

if [[ ! -e $DAQINTERFACE_SETTINGS ]]; then
   echo "Unable to find settings file \"$DAQINTERFACE_SETTINGS\"" >&2
   export DAQINTERFACE_USER_SOURCEFILE_ERRNO=1
   return 
fi

if [[ ! -e $DAQINTERFACE_KNOWN_BOARDREADERS_LIST ]]; then
   echo "Unable to find boardreaders list file \"$DAQINTERFACE_KNOWN_BOARDREADERS_LIST\"" >&2
   export DAQINTERFACE_USER_SOURCEFILE_ERRNO=2
   return 
fi

if [[ "$DAQINTERFACE_FHICL_DIRECTORY" != "IGNORED" && ! -e $DAQINTERFACE_FHICL_DIRECTORY ]]; then
   echo "Unable to find FHiCL configuration directory \"$DAQINTERFACE_FHICL_DIRECTORY\"" >&2
   export DAQINTERFACE_USER_SOURCEFILE_ERRNO=3
   return
elif [[ "$DAQINTERFACE_FHICL_DIRECTORY" == "IGNORED" ]]; then
   #echo "Put code here which sets up the database environment"
    source /daq/software/database/setup_database_e20s112.sh
    export ARTDAQ_DATABASE_CONFDIR=/daq/software/database/config-new
fi

export ARTDAQ_LOG_FHICL=/tmp/messagefacility_partition${DAQINTERFACE_PARTITION_NUMBER}_$(whoami).fcl
export HOSTNAME=$(hostname -s )-daq.fnal.gov

export DAQINTERFACE_USER_SOURCEFILE_ERRNO=0
