#!/usr/bin/env bash
good_run_number=12162
this_start=$(date +%s)

THIS_SCRIPT_DIR=$(realpath $(dirname "${BASH_SOURCE[0]}"))

partition=$(grep -Eo "export.*DAQINTERFACE_PARTITION_NUMBER=.*" ${THIS_SCRIPT_DIR}/user_sourcefile |cut -d"=" -f2)

function getStatus() {
  local current_status=$(status.sh | grep String | awk '{print $2}' | tr -d "'")
  echo $current_status
}

status=$(getStatus)

exclude_list=$(grep "See logfile " /daq/log/DAQInterface_partition${partition}.log \
  | grep -Eo '/icarus.*' | cut -d"-" -f1 | tr -d '/' | awk '{ printf("%s|",$1); }')

setdaqcomps.sh $(grep -vE "(${exclude_list}Event|Disp|label|trigger)" /daq/run_records/${good_run_number}/ranks.txt | awk '{printf("%s ", $3);}')

send_transition.sh boot boot_MinBias_VeryHighRate_multiple_art_processes.txt

status=$(getStatus)
while [ "$status" != 'booted' ]; do
  sleep 2
  status=$(getStatus)
  if [ "$status" == 'stopped' ]; then
    kill_daqinterface_on_partition.sh $partition
    exit 1
  fi
done

config_name=$(grep "Config name:" /daq/run_records/${good_run_number}/metadata.txt | cut -d":" -f2)
send_transition.sh config $config_name

sleep 60

status=$(getStatus)
while [ "$status" != 'ready' ]; do
  sleep 10
  status=$(getStatus)
  if [ "$status" == 'stopped' ]; then
    kill_daqinterface_on_partition.sh $partition
    exit 1
  fi
done

[[ -f $THIS_SCRIPT_DIR/show-launch-attempt-errors ]] && $THIS_SCRIPT_DIR/show-launch-attempt-errors

sleep 10

send_transition.sh start

sleep 2
status=$(getStatus)
while [ "$status" != 'running' ]; do
  sleep 2
  status=$(getStatus)
  if [ "$status" == 'stopped' ]; then
    kill_daqinterface_on_partition.sh $partition
    exit 1
  fi
done

this_stop=$(date +%s)
echo "DAQ started in $(( this_stop - this_start )) seconds."
