#!/usr/bin/env bash

if [ "$#" -ne 1 ]; then
    echo "Please specify the partition number, e.g."
    echo "./killdaq 7"
    exit
fi

for i in {01..04}; do
    echo "sbnd-evb${i}-daq: pkill -9 -f '^eventbuilder.*partition_number: $1$'"
    ssh sbnd-evb${i}-daq -f "pkill -9 -f '^eventbuilder.*partition_number: $1$'"
done

#ssh sbnd-evb01 -f 'killall -9 dispatcher'

echo "sbnd-wib01-daq: pkill -9 '^boardreader.*partition_number: $1$'"
ssh sbnd-wib01-daq -f "pkill -9 -f '^boardreader.*partition_number: $1$'"

echo "sbnd-evb04: pkill -9 '^boardreader.*partition_number: $1$'"
ssh sbnd-evb04 -f "pkill -9 -f '^boardreader.*partition_number: $1$'"

for i in {01..12}; do
    echo "sbnd-tpc${i}-daq: pkill -9 '^boardreader.*partition_number: $1$'"
    ssh sbnd-tpc${i}-daq -f "pkill -9 -f '^boardreader.*partition_number: $1$'"
done


for server in pds01 pds02 pds03 pds04 pds05 ptb01 ; do #crt01
    echo "sbnd-${server}-daq: pkill -9 '^boardreader.*partition_number: $1$'"
    ssh sbnd-${server}-daq -f "pkill -9 -f '^boardreader.*partition_number: $1$'"
done



for i in {01..04}; do
    echo "sbnd-evb${i}: ipcrm -a"
    ssh sbnd-evb${i}-daq -f 'ipcrm -a'
done

for i in 01 02; do
    echo "sbnd-daq${i}: ipcrm -a"
    ssh sbnd-daq${i}-daq -f 'ipcrm -a'
done

echo 'well done'
