#!/usr/bin/env bash

if [ "$#" -ne 1 ]; then
    echo "Please specify the partition number, e.g."
    echo "./killdaq 7"
    exit
fi

for i in {01..03}; do
    echo "sbnd-evb$i: pkill -9 -f '^eventbuilder.*partition_number: $1$'"
    ssh sbnd-evb$i -f "pkill -9 -f '^eventbuilder.*partition_number: $1$'"
done

#ssh sbnd-evb01 -f 'killall -9 dispatcher'

echo "sbnd-wib01: pkill -9 '^boardreader.*partition_number: $1$'"
ssh sbnd-wib01 -f "pkill -9 -f '^boardreader.*partition_number: $1$'"

echo "sbnd-evb04: pkill -9 '^boardreader.*partition_number: $1$'"
ssh sbnd-evb04 -f "pkill -9 -f '^boardreader.*partition_number: $1$'"

for i in {01..12}; do
    echo "sbnd-tpc$i: pkill -9 '^boardreader.*partition_number: $1$'"
    ssh sbnd-tpc$i -f "pkill -9 -f '^boardreader.*partition_number: $1$'"
done

for i in {01..03}; do
    echo "sbnd-evb$i: ipcrm -a"
    ssh sbnd-evb$i -f 'ipcrm -a'
done

echo 'well done'
