#!/usr/bin/env bash
#
#=====================================================================================
#Run with argument of which directory in configs you want to use. Defaults to standard
#=====================================================================================
CONFIGDIR="standard" 
if [ ! -z "$1" ]
    then
    CONFIGDIR=$1
else
    echo "Defaulting to configs/$CONFIGDIR"
fi

#if [ ! -d "$THIS_SBN_DAQ_DAQINTERFACE_DIR/configs/$CONFIGDIR" ]; then #check that config directory actually exists #Doesn't work if you're using the database though
#    echo "ERROR: configs/$CONFIGDIR does not exist. Please use existing directory as an argument or use no arguments to default to configs/standard."
#    echo "Stopping run script before I do anything"
#    exit 1
#fi

this_start=$(date +%s)

function getStatus()
{
  status=`status.sh | grep String | awk '{print $2}' | tr -d "'"`
#  [ $1 != "$status" ] && (echo $status)
  echo $status
}

getStatus "nil"
# [ $status == 'Existing'] && (kill_daqinterface_on_partition.sh 0; exit 0 )

#setdaqcomps.sh mbb02 wib101 wib102 wib103 wib104 wib105 wib106 wib201 wib202 wib203 wib204 wib205 wib206 wib301 wib302 wib303 wib304 wib305 wib306 wib401 wib402 wib403 wib404 wib405 wib406 tpc11 tpc10 tpc09 tpc08 tpc07 tpc06 tpc05 tpc04 tpc03 tpc02 tpc01 ntb01 ptb01PULL pmt01 pmt02 pmt03 pmt04 pmt05 pmt06 pmt07 pmt08 pmt09 spectdc crtNorthWallWestPULL crtNorthWallEastPULL crtflat3_southwestPULL crtflat3_eastPULL crtflat3_northPULL crtEastWallNorthTopPULL crtEastWallSouthBottomPULL crtSouthWallWestPULL crtSouthWallEastPULL crtWestWallNorthTopPULL crtWestWallSouthBottomPULL crtTopHighWallCentralPULL crtTopHighWallEastPULL crtTopHighWallNorthPULL crtTopHighWallSouthPULL crtTopHighWallWestPULL crtTopLowWallCentralPULL crtTopLowWallEastPULL crtTopLowWallNorthPULL crtTopLowWallSouthPULL crtTopLowWallWestPULL

#setdaqcomps.sh tpc11 tpc10 tpc09 tpc08 tpc07 tpc06 tpc05 tpc04 tpc03 tpc02 tpc01 ntb01
setdaqcomps.sh mbb02 wib101 wib102 wib103 wib104 wib105 wib106 wib201 wib202 wib203 wib204 wib205 wib206 wib301 wib302 wib303 wib304 wib305 wib306 wib401 wib402 wib403 wib404 wib405 wib406 tpc11 tpc10 tpc09 tpc08 tpc07 tpc06 tpc05 tpc04 tpc03 tpc02 tpc01 ntb01

#setdaqcomps.sh pmt01PUSH pmt02 pmt03 pmt04 pmt05 pmt06 pmt07 pmt08 pmt09 ptb01PULL


send_transition.sh boot boot.txt

getStatus "booting"

while [ "$status" != 'booted' ]
do
  sleep 2
  getStatus "booting"
	  [ "$status" == 'stopped' ] && (kill_daqinterface_on_partition.sh $DAQINTERFACE_PARTITION_NUMBER; exit 1 )
	done

send_transition.sh config $CONFIGDIR
getStatus "configuring"
while [ "$status" != 'ready' ]
do
  sleep 2
  getStatus "configuring"
  [ "$status" == 'stopped' ] && (kill_daqinterface_on_partition.sh $DAQINTERFACE_PARTITION_NUMBER; exit 1 )
  # [ "$status" == 'stopped' ] && ( exit 1 )
done

# report_datafile_location

send_transition.sh start
getStatus "starting"
sleep 2
getStatus "starting"
while [ "$status" != 'running' ]
do
  sleep 2
  getStatus "starting"
  [ "$status" == 'stopped' ] && (kill_daqinterface_on_partition.sh $DAQINTERFACE_PARTITION_NUMBER; exit 1 )
done

echo "Going to run disk monitoring/deletion script to monitor disk space usage and display warning message on tpc servers"
./macro_scripts/disk_monitor_delete.sh

this_stop=$(date +%s)
echo "DAQ started in $(( this_stop - this_start )) seconds."
