#!/usr/bin/env bash
this_start=$(date +%s)

THIS_SCRIPT_DIR=$(realpath $(dirname "${BASH_SOURCE[0]}"))

export PATH=$THIS_SCRIPT_DIR/overrides:$PATH

partition=$(grep -Eo "export.*DAQINTERFACE_PARTITION_NUMBER=.*" ${THIS_SCRIPT_DIR}/user_sourcefile |cut -d"=" -f2)

echo "Partition: $partition"

function getStatus() {
  local current_status=$(status.sh | grep String | awk '{print $2}' | tr -d "'")
  echo $current_status
}

status=$(getStatus)

exclude_list=$(grep "See logfile " /daq/log/DAQInterface_partition${partition}.log \
  | grep -Eo '/sbnd.*' | cut -d"-" -f1 | tr -d '/' | awk '{ printf("%s|",$1); }')

echo "Excluding: $exclude_list"

#setdaqcomps.sh $(grep -vE "(${exclude_list}Event|Disp|label|tpcww02)" /daq/run_records/${good_run_number}/ranks.txt | awk '{printf("%s ", $3);}')
setdaqcomps.sh ptb01PULL pmt01 pmt02 pmt03 pmt04 pmt05 pmt06 pmt07 pmt08 pmt09 spectdc ntb01 mbb02 wib101 wib102 wib103 wib104 wib105 wib106 wib201 wib202 wib203 wib204 wib205 wib206 wib301 wib302 wib303 wib304 wib305 wib306 wib401 wib402 wib403 wib404 wib405 wib406 tpc11 tpc10 tpc09 tpc08 tpc07 tpc06 tpc05 tpc04 tpc03 tpc02 tpc01

#setdaqcomps.sh ptb01PULL

echo "Booting up now...."
send_transition.sh boot boot_nodispatcher.txt
#send_transition.sh boot boot_nodqm.txt

echo "Finish booting...."

status=$(getStatus)
while [ "$status" != 'booted' ]; do
  sleep 2
  status=$(getStatus)
  if [ "$status" == 'stopped' ]; then
    kill_daqinterface_on_partition.sh $partition
    exit 1
  fi
done

CONFIGDIR="standard"
if [ ! -z "$1" ]
    then
    CONFIGDIR=$1
else
    echo "Defaulting to configs/$CONFIGDIR"
fi

echo "Config name: $CONFIGDIR"

send_transition.sh config $CONFIGDIR

sleep 10

status=$(getStatus)
while [ "$status" != 'ready' ]; do
  sleep 10
  status=$(getStatus)
  if [ "$status" == 'stopped' ]; then
    kill_daqinterface_on_partition.sh $partition
    exit 1
  fi
done

[[ -f $THIS_SCRIPT_DIR/show-launch-attempt-errors ]] && $THIS_SCRIPT_DIR/show-launch-attempt-errors

sleep 10

send_transition.sh start

sleep 2
status=$(getStatus)
while [ "$status" != 'running' ]; do
  sleep 2
  status=$(getStatus)
  if [ "$status" == 'stopped' ]; then
    kill_daqinterface_on_partition.sh $partition
    exit 1
  fi
done

this_stop=$(date +%s)
echo "DAQ started in $(( this_stop - this_start )) seconds."
