#!/usr/bin/env bash

THIS_SCRIPT_DIR=$(realpath $(dirname "${BASH_SOURCE[0]}"))

partition=$(grep -Eo "export.*DAQINTERFACE_PARTITION_NUMBER=.*" ${THIS_SCRIPT_DIR}/user_sourcefile |cut -d"=" -f2)

grep -E "%MSG-e" -A1 /daq/log/pmt/launch_attempt*$(ls -r /daq/log/pmt/launch_attempt_sbnd-evb*-daq_sbnd_partition${partition}* |head -1 |awk -F'_' '{print $NF}')
