#!/bin/bash

rgang 'sbnd-{tpc{01-28},pmt{01-10},crt{01-10}}-daq' 'killall boardreader'

rgang 'sbnd-evb{01-06}-daq' 'killall eventbuilder'
rgang 'sbnd-evb{01-06}-daq' 'killall datalogger'
rgang 'sbnd-evb{01-06}-daq' 'killall dispatcher'
rgang 'sbnd-evb{01-06}-daq' 'killall art'

kill -INT $(ps -ef |grep -i "daqinterface.py" |grep -v grep |tr -s " "|cut -d" " -f2)

rgang 'sbnd-{tpc{01-28},pmt{01-10},crt{01-10}}-daq' 'killall -9 boardreader'

rgang 'sbnd-evb{01-06}-daq' 'killall -9 eventbuilder'
rgang 'sbnd-evb{01-06}-daq' 'killall -9 datalogger'
rgang 'sbnd-evb{01-06}-daq' 'killall -9 dispatcher'
rgang 'sbnd-evb{01-06}-daq' 'killall -9 art'

kill -9 $(ps -ef |grep -i "daqinterface.py" |grep -v grep |tr -s " "|cut -d" " -f2)

rgang 'sbnd-{tpc{01-28},pmt{01-10},crt{01-10},evb{01-06}}-daq' 'killall -9 trace_cntl'
rgang 'sbnd-{tpc{01-28},pmt{01-10},crt{01-10},evb{01-06}}-daq' 'ipcrm -a'


