{
 "title": "Shifter DAQ Status",
 "description": "This dashboard is the one intended for use by the shifter. The others are generally expert level :)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last Run Number (partition 1)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "sbnd.partition1.run_number" }
   ]
  },
  {
   "title": "Total Event Rates",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "target": "alias(averageSeries(keepLastValue(sbnd.*tdc*, 10)), 'TDC Avg Rate')"
    },
    {
     "target": "alias(averageSeries(keepLastValue(sbnd.*pmt*.BoardReader.*.Fragment_Rate, 10)), 'PMT Avg Fragment Rate')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.evb*.*.Event_Rate, 10)), 'EventBuilder Event Rate')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.disp01.*.Event_Rate)), 'Dispatcher Event Rate')"
    }
   ]
  },
  {
   "title": "Beam Early Warning Signals ",
   "type": "gauge",
   "description": "Rate of the beam signals transmitted through the White Rabbit network",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias(sbnd.daq02.*.*.WR_CLK02_SPEC_DIO_gatedBES.DIO_Channel_4_Rates, 'BNB Gated BES')"
    },
    {
     "target": "alias(sbnd.daq02.*.*.WR_CLK02_SPEC_DIO_$1D.DIO_Channel_1_Rates, 'BNB $1D')"
    },
    {
     "target": "alias(sbnd.daq02.BoardReader.*.WR_CLK02_SPEC_DIO_$74.DIO_Channel_3_Rates, 'NuMI MIBS $74')"
    },
    {
     "target": "alias(averageSeries(sbnd.daq02.BoardReader.*.WR_CLK02_SPEC_DIO_$AE.DIO_Channel_2_Rates), 'NuMI $AD')"
    }
   ]
  },
  {
   "title": "Events Released To Art From This Run",
   "type": "table-old",
   "description": "This shows the number of events collected for this run.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.evb*.*.Events_Released_to_art_this_run, 10)), 'Events Released to art in EventBuilders')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.dl*.*.Events_Released_to_art_this_run, 10)), 'Events Released to art in DataLoggers')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.disp*.*.Events_Released_to_art_this_run, 10)), 'Events Released to art in Dispatchers')"
    }
   ]
  },
  {
   "title": "Incomplete Events Released To Art From This Run",
   "type": "table-old",
   "description": "In the ideal case, there are no incomplete events. If you start seeing incomplete events, make note of this in the ECL!",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.evb*.*.Incomplete_Events_Released_to_art_this_run, 10)), 'Incomplete Events in EventBuilders')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.dl*.*.Incomplete_Events_Released_to_art_this_run, 10)), 'Inomplete Events in DataLoggers')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.disp01.*.Incomplete_Events_Released_to_art_this_run, 10)), 'Inomplete Events in Dispatchers')"
    }
   ]
  },
  {
   "title": "Events with empty fragments  [%]",
   "type": "stat",
   "description": "the rate of the total empty fragments collected normalized to the total number of events collected",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } }
  },
  {
   "title": "/data Usage Monitor",
   "type": "gauge",
   "description": "Shows how much of the /data area on evb01 is being used.\n\nIt's set to go orange above 60%, meaning take note, and it's set to go red above 95%, meaning alarm.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(sbnd.sbnd-evb01.data.Percent_Used, 'sbnd-evb01')"
    },
    {
     "target": "alias(sbnd.sbnd-evb02.data.Percent_Used, 'icaurs-evb02')"
    },
    {
     "target": "alias(sbnd.sbnd-evb03.data.Percent_Used, 'sbnd-evb03')"
    },
    {
     "target": "alias(sbnd.sbnd-evb04.data.Percent_Used, 'sbnd-evb04')"
    },
    {
     "target": "alias(sbnd.sbnd-evb05.data.Percent_Used, 'sbnd-evb05')"
    },
    {
     "target": "sbnd.sbnd-evb06.data.Percent_Used"
    }
   ]
  }
 ]
}