{
 "title": "WR-TDC Monitor",
 "description": "This dashboard is the one intended for use by the shifter. The others are generally expert level :)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Run Number (P 7)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "sbnd.partition7.run_number" }
   ]
  },
  {
   "title": "TDC Monitor",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 1 },
   "targets": [
    {
     "target": "alias(movingAverage(sbnd.tdc.BoardReader.0.Fragment_Rate, 1), 'Artdaq Fragment  Rate')"
    },
    {
     "target": "alias(movingAverage(sbnd.tdc.BoardReader.0.Fragments_Sent, 1), 'TDC Fragment Rate')"
    }
   ]
  },
  {
   "title": "Collected Events Monitor",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "target": "alias(keepLastValue(sbnd.tdc.*.0.Fragment_Count, 10), 'Fragments Sent from WR-TDC BoardReader')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.evb*.*.Events_Released_to_art_this_run, 10)), 'Events Released to art in EventBuilders')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.dl*.*.Events_Released_to_art_this_run, 10)), 'Events Released to art in DataLoggers')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.disp*.*.Events_Released_to_art_this_run, 10)), 'Events Released to art in Dispatchers')"
    }
   ]
  },
  {
   "title": "Fragment Watcher",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(sumSeries(sbnd.evb*.EventBuilder*_art*.EventsWithEmptyFragments), 3)"
    },
    {
     "target": "aliasByNode(sumSeries(sbnd.evb*.EventBuilder*_art*.EventsWithMissingFragments), 3)"
    },
    {
     "target": "aliasByNode(sumSeries(sbnd.evb*.EventBuilder*_art*.EventsProcessed), 3)"
    }
   ]
  },
  {
   "title": "Fragment Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.tdc.BoardReader.0.Fragment_Rate, 1), 4)"
    }
   ]
  },
  {
   "title": "TDC Sample Rate (all channels)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sumSeries(sbnd.tdc.BoardReader.0.TDC_Chan*_Sample_Rate, *), 1), 4)"
    }
   ]
  },
  { "title": "WR TDC  Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "TDC Sample Rate",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(sbnd.tdc.BoardReader.*.TDC_Chan*_Sample_Rate, 10), 4)"
    }
   ]
  },
  {
   "title": "Missed & Drained Samples",
   "type": "table",
   "gridPos": { "h": 13, "w": 4, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(sbnd.tdc.BoardReader.0.TDC_Chan*_Sample_Missed_Total, 10), 4)"
    },
    {
     "target": "aliasByNode(keepLastValue(sbnd.tdc.BoardReader.0.TDC_Chan*_Sample_Drained_Total, 10), 4)"
    }
   ]
  },
  {
   "title": "Samples Total & Last Sequence",
   "type": "table",
   "gridPos": { "h": 13, "w": 5, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(sbnd.tdc.BoardReader.0.TDC_Chan*_Sample_Read_Total, 10), 4)"
    },
    {
     "target": "aliasByNode(keepLastValue(sbnd.tdc.BoardReader.0.TDC_Chan*_Sample_Last_Sequence, 10), 4)"
    }
   ]
  },
  {
   "title": "WR Sync Status",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "target": "alias(sbnd.tdc.BoardReader.0.WR_Time_Synced, 'WR')"
    }
   ]
  },
  {
   "title": "Request Response Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.tdc.BoardReader.0.Request_Response_Time, 1), 4)"
    }
   ]
  },
  {
   "title": "SPEC Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(sbnd.tdc.BoardReader.0.SPEC_Temperature, 20), 4)"
    }
   ]
  },
  { "title": "Event Building", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "TDC Sample to Artdaq Fragment Time",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(movingAverage(sbnd.tdc.BoardReader.0.Fragment_Create_Time_-_Average, 1), 'Avg')"
    },
    {
     "target": "alias(movingAverage(sbnd.tdc.BoardReader.0.Fragment_Create_Time_-_Max, 1), 'Max')"
    }
   ]
  },
  {
   "title": "Request Response Time",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "alias(movingAverage(sbnd.tdc.BoardReader.0.Request_Response_Time, 1), 'RRT')"
    }
   ]
  },
  {
   "title": "BoardReader applyRequests() loop Avg Time",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "alias(movingAverage(sbnd.tdc.BoardReader.0.Avg_Request_Response_Wait_Time, 1), 'APLY')"
    }
   ]
  },
  {
   "title": "TDC Sample Rates",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasSub(movingAverage(sbnd.tdc.BoardReader.0.TDC_Chan*_Sample_Rate, 1), '.*Chan(\\d+).*', '\\1')"
    }
   ]
  },
  {
   "title": "EVB  Full Buffers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.evb*.EventBuilder*.Shared_Memory_Full_Buffers, 1), 2)"
    }
   ]
  },
  {
   "title": "EVB Memory Full %",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasSub(keepLastValue(sbnd.evb*.EventBuilder*.Shared_Memory_Full_%, 10), '.*Builder(\\d+).*', '\\1')"
    }
   ]
  },
  {
   "title": "EVB  Pending Buffers",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 41 },
   "targets": [
    {
     "target": "aliasSub(movingAverage(sbnd.evb*.EventBuilder*.Shared_Memory_Pending_Buffers, 1), '.*Builder(\\d+).*', '\\1')"
    }
   ]
  },
  {
   "title": "EVB  Pending Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.evb0*.EventBuilder*.Shared_Memory_Pending_Buffers, 1), 2)"
    }
   ]
  },
  { "title": "PoolBuffer Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Free Blocks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "target": "aliasByNode(sbnd.tdc.BoardReader.0.PoolBuffer_Free_Block_Count, 4)"
    }
   ]
  },
  {
   "title": "Fully Drained",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(sbnd.tdc.BoardReader.0.PoolBuffer_Fully_Drained_Count, 4)"
    }
   ]
  },
  {
   "title": "Low Watermark",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.tdc.BoardReader.0.PoolBuffer_Low_Watermark, 1), 4)"
    }
   ]
  },
  { "title": "WR TDC  Monitor Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "TDC Sample Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(removeBelowValue(movingAverage(sbnd.tdc.BoardReader.0.TDC_Chan*_Sample_Rate, 1), 0.001), 4)"
    }
   ]
  },
  {
   "title": "TDC Sample Time Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.tdc.BoardReader.0.TDC_Chan*_Sample_Time_Lag, 1), 4)"
    }
   ]
  },
  {
   "title": "TDC Sequence Gaps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(sbnd.tdc.BoardReader.0.TDC_Chan*_Sequence_Gap, 4)"
    }
   ]
  },
  {
   "title": "TDC Laggy Samples",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "aliasByNode(sbnd.tdc.BoardReader.0.TDC_Chan*_Laggy_Samples, 4)"
    }
   ]
  },
  {
   "title": "Board Reader Core Monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "BoardReader getNext() Avg Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "target": "aliasByNode(movingAverage(sbnd.tdc.BoardReader.0.Avg_Output_Wait_Time, 1), 4)"
      }
     ]
    },
    {
     "title": "Artdaq Fragment Buffer % Full",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "target": "aliasByNode(movingAverage(sbnd.tdc.BoardReader.0.Fragment_Buffer_Full_%, 1), 4)"
      }
     ]
    },
    {
     "title": "BoardReader applyRequests() loop Avg Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "target": "aliasByNode(movingAverage(removeAboveValue(sbnd.tdc.BoardReader.0.Avg_Request_Response_Wait_Time, 0.5), 1), 4)"
      }
     ]
    },
    {
     "title": "BoardReader Fragments per getNext()",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "aliasByNode(movingAverage(sbnd.tdc.BoardReader.0.Avg_Frags_Per_Read, 1), 4)"
      }
     ]
    },
    {
     "title": "BoardReader sendFragment() Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "target": "aliasByNode(movingAverage(sbnd.tdc.BoardReader.0.Avg_Output_Wait_Time, 1), 4)"
      }
     ]
    }
   ]
  },
  { "title": "Board Reader Core Extra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Frafments Per Non Empty Container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "target": "alias(sbnd.tdc.BoardReader.0.Fragments_Per_Not_Empty_Container_-_Average, 'Avg')"
    },
    {
     "target": "alias(sbnd.tdc.BoardReader.0.Fragments_Per_Not_Empty_Container_-_Max, 'Max')"
    },
    {
     "target": "alias(sbnd.tdc.BoardReader.0.Fragments_Per_Not_Empty_Container_-_Min, 'Min')"
    }
   ]
  },
  {
   "title": "Frafments Per Non Empty Container",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "target": "alias(sbnd.tdc.BoardReader.0.Fragments_Per_Not_Empty_Container_-_Average, 'Avg')"
    },
    {
     "target": "alias(sbnd.tdc.BoardReader.0.Fragments_Per_Not_Empty_Container_-_Max, 'Max')"
    },
    {
     "target": "alias(sbnd.tdc.BoardReader.0.Fragments_Per_Not_Empty_Container_-_Min, 'Min')"
    }
   ]
  },
  {
   "title": "No data window around pull the request window",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "target": "aliasByNode(removeAboveValue(sbnd.tdc.BoardReader.0.No_Data_Window_Around_Request, 5000000000), 4)"
    },
    {
     "target": "aliasByNode(removeAboveValue(sbnd.tdc.BoardReader.0.No_Data_After_End_Window, 1000000000), 4)"
    },
    {
     "target": "aliasByNode(removeAboveValue(sbnd.tdc.BoardReader.0.No_Data_Before_Begin_Window, 1000000000), 4)"
    }
   ]
  },
  {
   "title": "Board Reader Core Request Monitor",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "target": "aliasByNode(removeBelowValue(movingAverage(sbnd.tdc.BoardReader.0.Requests_Yielding_Empty_Fragments, 1), 0.01), 4)"
    },
    {
     "target": "aliasByNode(removeBelowValue(movingAverage(sbnd.tdc.BoardReader.0.Requests_With_Missing_Data, 1), 0.01), 4)"
    },
    {
     "target": "aliasByNode(removeBelowValue(movingAverage(sbnd.tdc.BoardReader.0.Requests_With_Window_Timeout, 1), 0.01), 4)"
    },
    {
     "target": "aliasByNode(removeBelowValue(movingAverage(sbnd.*.BoardReader.0.Fragment_Rate, 1), 0.01), 4)"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "/data Usage Monitor",
   "type": "gauge",
   "description": "Shows how much of the /data area on evb01 is being used.\n\nIt's set to go orange above 60%, meaning take note, and it's set to go red above 95%, meaning alarm.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(sbnd.sbnd-evb01.data.Percent_Used, 'sbnd-evb01')"
    },
    {
     "target": "alias(sbnd.sbnd-evb02.data.Percent_Used, 'icaurs-evb02')"
    },
    {
     "target": "alias(sbnd.sbnd-evb03.data.Percent_Used, 'sbnd-evb03')"
    },
    {
     "target": "alias(sbnd.sbnd-evb04.data.Percent_Used, 'sbnd-evb04')"
    },
    {
     "target": "alias(sbnd.sbnd-evb05.data.Percent_Used, 'sbnd-evb05')"
    },
    {
     "target": "sbnd.sbnd-evb06.data.Percent_Used"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.tdc.BoardReader.0.Process_CPU_Usage, 1), 4)"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.tdc.BoardReader.0.Process_RAM_Usage, 1), 4)"
    }
   ]
  }
 ]
}