#!/usr/bin/env bash

function getStatus()
{
  status=`status.sh | sed -n '3p' | awk '{print $2}' | tr -d "'"`
  echo $status
}

send_transition.sh stop
getStatus
while [ $status != 'ready' ]
do
  sleep 1
  getStatus
done

send_transition.sh terminate
getStatus
while [ $status != 'stopped' ]
do
  sleep 1
  getStatus
done

